Repository andela/ah-frontend-valkyrie, pull requests merged in 2019-02, with the labels that each got.

#4 #162633452 Set up redux
  .gitignore
  package-lock.json
  package.json
  src/App.js
  src/actions/index.js
  src/index.js
  src/reducers/articlesReducer.js
  src/reducers/rootReducer.js
  src/store/index.js
Labels: Ready for Reviews

#3 #162633454 Integrate repo to CI services
  .codeclimate.yml
  .gitignore
  .hound.yml
  .scss-lint.yml
  .travis.yml
  README.md
  package-lock.json
Labels: Finished

#7 #162633456 setup SASS
  package.json
  src/App.js
  src/assets/css/style.css
  src/assets/scss/style.scss
  src/index.js
  webpack.config.js
Labels: Ready for Reviews

#5 #162633455 Set up react router 4
  .eslintrc
  .gitignore
  .travis.yml
  package-lock.json
  package.json
  src/App.js
  src/components/auth/Login.js
  src/components/auth/Register.js
  src/components/common/TextInputField.js
  src/components/layout/Landing.js
  src/components/layout/Navbar.js
  src/index.html
  webpack.config.js
Labels: Ready for Reviews

#8 #162633453 Setup react testing environment
  .gitignore
  .travis.yml
  package.json
  src/App.test.js
  tests/enzyme.config.js
  tests/jest.config.js
Labels: Ready for Reviews

#6 Heroku deployment
  .gitignore
  .travis.yml
  Procfile
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/index.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov-report/src/App.js.html
  coverage/lcov-report/src/components/auth/Login.js.html
  coverage/lcov-report/src/components/auth/Register.js.html
  coverage/lcov-report/src/components/auth/index.html
  coverage/lcov-report/src/components/common/TextInputField.js.html
  coverage/lcov-report/src/components/common/index.html
  coverage/lcov-report/src/components/layout/Landing.js.html
  coverage/lcov-report/src/components/layout/Navbar.js.html
  coverage/lcov-report/src/components/layout/index.html
  coverage/lcov-report/src/index.html
  coverage/lcov.info
  package-lock.json
  package.json
  server.js
  src/components/layout/Navbar.js
  src/index.js
  webpack.config.js
Labels: WIP

#14 #162633460 Implement User login
  .babelrc
  .eslintrc
  .gitignore
  .hound.yml
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/index.html
  coverage/lcov-report/src/App.js.html
  coverage/lcov-report/src/components/auth/Login.js.html
  coverage/lcov-report/src/components/auth/Register.js.html
  coverage/lcov-report/src/components/auth/index.html
  coverage/lcov-report/src/components/common/TextInputField.js.html
  coverage/lcov-report/src/components/common/index.html
  coverage/lcov-report/src/components/layout/Landing.js.html
  coverage/lcov-report/src/components/layout/Navbar.js.html
  coverage/lcov-report/src/components/layout/index.html
  coverage/lcov-report/src/index.html
  coverage/lcov.info
  package-lock.json
  package.json
  src/App.js
  src/App.test.js
  src/__snapshots__/App.test.js.snap
  src/actions/index.js
  src/actions/loginActions.js
  src/actions/tests/loginActions.test.js
  src/assets/images/profile.png
  src/components/Alert/Alert.js
  src/components/auth/Login.js
  src/components/auth/login/LoginForm.js
  src/components/auth/styles/Login.css
  src/components/auth/tests/Login.test.js
  src/components/auth/tests/__snapshots__/Login.test.js.snap
  src/components/common/Button.js
  src/components/common/Modal.js
  src/components/common/TextInputField.js
  src/components/common/tests/Button.test.js
  src/components/common/tests/TextInputField.test.js
  src/components/common/tests/__snapshots__/Button.test.js.snap
  src/components/common/tests/__snapshots__/TextInputField.test.js.snap
  src/components/layout/Navbar.js
  src/components/layout/styles/Navbar.css
  src/index.html
  src/reducers/articlesReducer.js
  src/reducers/loginRecucer.js
  src/reducers/rootReducer.js
  src/reducers/tests/loginReducer.test.js
  src/reducers/tests/rootReducer.test.js
  src/store/index.js
  tests/enzyme.config.js
  tests/jest.config.js
  webpack.config.js
Labels: Ready for Reviews

#18 #162633459 Implement Reset Password Functionality
  .eslintrc
  .gitignore
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/index.html
  coverage/lcov-report/src/App.js.html
  coverage/lcov-report/src/components/auth/Login.js.html
  coverage/lcov-report/src/components/auth/Register.js.html
  coverage/lcov-report/src/components/auth/index.html
  coverage/lcov-report/src/components/common/TextInputField.js.html
  coverage/lcov-report/src/components/common/index.html
  coverage/lcov-report/src/components/layout/Landing.js.html
  coverage/lcov-report/src/components/layout/Navbar.js.html
  coverage/lcov-report/src/components/layout/index.html
  coverage/lcov-report/src/index.html
  coverage/lcov.info
  package-lock.json
  package.json
  src/App.js
  src/actions/ChangePasswordAction.js
  src/actions/ChangePasswordAction.test.js
  src/actions/ResetPasswordLinkAction.js
  src/actions/ResetPasswordLinkAction.test.js
  src/actions/actionTypes.js
  src/assets/css/style.css
  src/components/auth/Login.js
  src/components/auth/__snapshots__/change_password.test.js.snap
  src/components/auth/__snapshots__/reset_password.test.js.snap
  src/components/auth/change_password.js
  src/components/auth/change_password.test.js
  src/components/auth/reset_password.js
  src/components/auth/reset_password.test.js
  src/components/auth/styles/passwordReset.css
  src/components/common/TextInputField.js
  src/components/common/tests/TextInputField.test.js
  src/components/common/tests/__snapshots__/TextInputField.test.js.snap
  src/components/layout/Landing.js
  src/components/layout/Navbar.js
  src/reducers/passwordResetReducer.js
  src/reducers/passwordResetReducer.test.js
  src/reducers/rootReducer.js
  webpack.config.js
Labels: Finished

#19 162633464: Users should be able to create articles
  .codeclimate.yml
  .env
  .gitignore
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/index.html
  coverage/lcov-report/src/App.js.html
  coverage/lcov-report/src/components/auth/Login.js.html
  coverage/lcov-report/src/components/auth/Register.js.html
  coverage/lcov-report/src/components/auth/index.html
  coverage/lcov-report/src/components/common/TextInputField.js.html
  coverage/lcov-report/src/components/common/index.html
  coverage/lcov-report/src/components/layout/Landing.js.html
  coverage/lcov-report/src/components/layout/Navbar.js.html
  coverage/lcov-report/src/components/layout/index.html
  coverage/lcov-report/src/index.html
  coverage/lcov.info
  package-lock.json
  package.json
  src/App.js
  src/actions/articleActions.js
  src/assets/css/style.css
  src/components/articles/Article.js
  src/components/articles/CreateArticle.js
  src/components/articles/CreateArticleForm.js
  src/components/articles/SingleArticle.js
  src/components/articles/SingleArticleItem.js
  src/components/articles/SingleArticleView.js
  src/components/articles/UpdateArticle.js
  src/components/articles/UpdateArticleForm.js
  src/components/articles/test/Article.test.js
  src/components/articles/test/CreateArticleForm.test.js
  src/components/articles/test/SingleArticle.test.js
  src/components/articles/test/UpdateArticle.test.js
  src/components/articles/test/UpdateArticleForm.test.js
  src/components/articles/test/__snapshots__/Article.test.js.snap
  src/components/articles/test/__snapshots__/CreateArticleForm.test.js.snap
  src/components/articles/test/__snapshots__/SingleArticle.test.js.snap
  src/components/articles/test/__snapshots__/createArticle.test.js.snap
  src/components/articles/test/createArticle.test.js
  src/components/auth/Login.js
  src/components/layout/Landing.js
  src/components/layout/Landing.test.js
  src/components/layout/Navbar.js
  src/components/layout/Sidebar.js
  src/components/utils/QuilModules.js
  src/components/utils/http.js
  src/components/utils/isEmpty.js
  src/index.html
  src/reducers/articleReducer.js
  src/reducers/rootReducer.js
  tests/jest.config.js
Labels: Ready for Reviews

#17 #162633461 Implements Social Authentication
  .codeclimate.yml
  .env
  .eslintrc
  .eslintrc.json
  .gitignore
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/index.html
  coverage/lcov-report/src/App.js.html
  coverage/lcov-report/src/components/auth/Login.js.html
  coverage/lcov-report/src/components/auth/Register.js.html
  coverage/lcov-report/src/components/auth/index.html
  coverage/lcov-report/src/components/common/TextInputField.js.html
  coverage/lcov-report/src/components/common/index.html
  coverage/lcov-report/src/components/layout/Landing.js.html
  coverage/lcov-report/src/components/layout/Navbar.js.html
  coverage/lcov-report/src/components/layout/index.html
  coverage/lcov-report/src/index.html
  coverage/lcov.info
  package-lock.json
  package.json
  src/App.js
  src/__tests__/authTests/socialActions.test.js
  src/__tests__/authTests/socialAuth.test.js
  src/actions/index.js
  src/actions/loginActions.js
  src/actions/socialActions.js
  src/actions/tests/loginActions.test.js
  src/actions/types.js
  src/components/Alert/Alert.js
  src/components/auth/Login.js
  src/components/auth/Register.js
  src/components/auth/RegisterForm.js
  src/components/auth/login/LoginForm.js
  src/components/auth/social/SocialAuth.js
  src/components/auth/social/sampleToken.js
  src/components/auth/tests/Login.test.js
  src/components/common/Button.js
  src/components/common/TextInputField.js
  src/components/common/tests/TextInputField.test.js
  src/components/common/tests/__snapshots__/Button.test.js.snap
  src/components/common/tests/__snapshots__/TextInputField.test.js.snap
  src/components/layout/Navbar.js
  src/components/profile/EditProfileForm.js
  src/components/profile/ProfileDashboard.js
  src/components/profile/tests/EditProfile.test.js
  src/reducers/errorReducer.js
  src/reducers/loginRecucer.js
  src/reducers/rootReducer.js
  src/reducers/tests/loginReducer.test.js
  src/utils/setAuthToken.js
  src/validations/isEmpty.js
  tests/jest.config.js
  webpack.config.js
Labels: Finished

#25 #162633464 Increase create article coverage
  .env
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/index.html
  coverage/lcov-report/src/App.js.html
  coverage/lcov-report/src/components/auth/Login.js.html
  coverage/lcov-report/src/components/auth/Register.js.html
  coverage/lcov-report/src/components/auth/index.html
  coverage/lcov-report/src/components/common/TextInputField.js.html
  coverage/lcov-report/src/components/common/index.html
  coverage/lcov-report/src/components/layout/Landing.js.html
  coverage/lcov-report/src/components/layout/Navbar.js.html
  coverage/lcov-report/src/components/layout/index.html
  coverage/lcov-report/src/index.html
  coverage/lcov.info
  package-lock.json
  package.json
  src/__snapshots__/App.test.js.snap
  src/actions/articleActions.js
  src/components/articles/Article.js
  src/components/articles/CreateArticle.js
  src/components/articles/CreateArticleForm.js
  src/components/articles/SingleArticle.js
  src/components/articles/SingleArticleItem.js
  src/components/articles/SingleArticleView.js
  src/components/articles/UpdateArticle.js
  src/components/articles/test/Article.test.js
  src/components/articles/test/SingleArticle.test.js
  src/components/articles/test/SingleArticleItem.test.js
  src/components/articles/test/SingleArticleView.test.js
  src/components/articles/test/UpdateArticle.test.js
  src/components/articles/test/__snapshots__/Article.test.js.snap
  src/components/articles/test/__snapshots__/CreateArticleForm.test.js.snap
  src/components/articles/test/__snapshots__/SingleArticle.test.js.snap
  src/components/articles/test/__snapshots__/createArticle.test.js.snap
  src/components/articles/test/createArticle.test.js
  src/components/auth/__snapshots__/change_password.test.js.snap
  src/components/auth/__snapshots__/reset_password.test.js.snap
  src/components/common/Loader.js
  src/components/common/Loader.test.js
  src/components/common/Modal.test.js
  src/components/common/tests/__snapshots__/Button.test.js.snap
  src/components/common/tests/__snapshots__/RegisterFields.test.js.snap
  src/components/common/tests/__snapshots__/TextInputField.test.js.snap
  src/components/layout/Sidebar.test.js
  src/components/utils/http.js
  src/reducers/articleReducer.js
Labels: Ready for Reviews
