Repository andela/ah-frontend-valkyrie, pull requests merged in 2019-03, with the labels that each got.

#28 #162633475 Add Search functionality to article list
  server.js
  src/App.js
  src/actions/articleActions.js
  src/assets/css/style.css
  src/components/articles/SingleArticleView.js
  src/components/layout/Sidebar.js
  src/components/search/RecentArticles.js
  src/components/search/SearchArticle.js
  src/components/search/SearchArticleData.js
  src/components/search/SearchArticleForm.js
  src/components/search/tests/RecentArticles.test.js
  src/components/search/tests/SearchArticle.test.js
  src/components/search/tests/SearchArticleData.test.js
  src/components/search/tests/SearchArticleForm.test.js
  src/components/utils/http.js
  src/reducers/articleReducer.js
  src/reducers/articlesReducer.js
Labels: Ready for Reviews

#27 #162633467 Implement article pagination
  .codeclimate.yml
  .eslintrc
  .eslintrc.json
  package.json
  src/App.js
  src/actions/ChangePasswordAction.js
  src/actions/actionTypes.js
  src/actions/articleActions.js
  src/actions/tests/articleActions.test.js
  src/components/articles/Article.js
  src/components/articles/test/Article.test.js
  src/components/auth/Login.js
  src/components/layout/Landing.js
  src/components/layout/Landing.test.js
  src/components/layout/Navbar.js
  src/components/layout/Sidebar.js
  src/components/pagination/Pagination.js
  src/components/pagination/pageItem.js
  src/components/pagination/specialPageItem.js
  src/components/pagination/styles/pagination.css
  src/components/pagination/tests/SpecialPaginationItem.test.js
  src/components/pagination/tests/pagination.test.js
  src/components/pagination/tests/paginationItem.test.js
  src/components/profile/ProfileNav.js
  src/components/profile/tests/ProfileTabs.test.js
  src/components/search/tests/SearchArticleForm.test.js
  src/components/utils/AuthUser.js
  src/components/utils/QuilModules.js
  src/components/utils/http.js
  src/reducers/articleReducer.js
  src/reducers/passwordResetReducer.js
  src/reducers/passwordResetReducer.test.js
  src/utils/paginationUtils.js
  src/utils/tests/paginationUtils.test.js
  tests/jest.config.js
Labels: Ready for Reviews

#30 #162633465 Implements rating articles
  .gitignore
  package.json
  src/__tests__/rateTests/RateArticle.test.js
  src/__tests__/rateTests/ratingActions.test.js
  src/actions/loginActions.js
  src/actions/rating/ratingActions.js
  src/actions/types.js
  src/assets/css/style.css
  src/components/articles/AverageRating.js
  src/components/articles/RateArticle.js
  src/components/articles/SingleArticle.js
  src/components/articles/SingleArticleItem.js
  src/components/articles/SingleArticleView.js
  src/components/auth/Login.js
  src/components/layout/Sidebar.js
  src/components/profile/ProfileDashboard.js
  src/reducers/rateReducer.js
  src/reducers/rootReducer.js
  src/store/index.js
Labels: Ready for Reviews

#35 #162633471: Enable sharing of articles
  src/actions/articleActions.js
  src/actions/socialShareActions.js
  src/actions/tests/articleActions.test.js
  src/actions/tests/socialShareActions.test.js
  src/components/articles/SingleArticleView.js
  src/components/articles/styles/SingleArticle.css
  src/components/layout/Sidebar.test.js
  src/components/socialShare/SocialShare.js
  src/components/socialShare/SocialShareIcon.js
  src/components/socialShare/tests/socialShare.test.js
  src/components/socialShare/tests/socialShareIcon.test.js
  src/components/utils/http.js
  src/index.html
  src/reducers/rootReducer.js
  src/reducers/socialShareReducer.js
  src/reducers/tests/articleReducer.test.js
  src/reducers/tests/socialShareReducer.test.js
Labels: Ready for Reviews

#31 #162633482 Like-Unlike a comment
  .gitignore
  package.json
  server.js
  src/actions/articleActions.js
  src/assets/css/style.css
  src/components/articles/SingleArticle.js
  src/components/articles/SingleArticleView.js
  src/components/comments/SingleComment.js
  src/components/comments/UserReactions.js
  src/components/comments/actions/AsyncActions.test.js
  src/components/comments/actions/action_types.js
  src/components/comments/actions/actions.js
  src/components/comments/actions/syncActions.test.js
  src/components/comments/reducers/CommentReducer.test.js
  src/components/comments/reducers/UserReactionsReducer.js
  src/components/comments/reducers/UserReactionsReducer.test.js
  src/components/comments/reducers/commentReducer.js
  src/components/comments/reducers/commentReducerError.test.js
  src/components/comments/tests/CommentList.test.js
  src/components/comments/tests/CreateComment.test.js
  src/components/comments/tests/EditComment.test.js
  src/components/comments/tests/SingleComment.test.js
  src/components/comments/tests/UserReactions.test.js
  src/components/layout/Landing.js
  src/components/layout/Navbar.js
  src/components/utils/AuthUser.js
  src/reducers/articleReducer.js
  src/reducers/rootReducer.js
  tests/jest.config.js
Labels: Finished, Ready for Reviews

#24 #162633468 Implements Like or dislike articles by a user
  package-lock.json
  src/actions/ChangePasswordAction.test.js
  src/actions/ResetPasswordLinkAction.js
  src/actions/ResetPasswordLinkAction.test.js
  src/actions/likeArticleActions.js
  src/actions/tests/likeActions.test.js
  src/components/articles/CreateArticle.js
  src/components/articles/LikeArticle.js
  src/components/articles/SingleArticleView.js
  src/components/articles/UpdateArticle.js
  src/components/articles/UpdateArticleForm.js
  src/components/articles/test/CreateArticleForm.test.js
  src/components/articles/test/LikeArticle.test.js
  src/components/articles/test/UpdateArticle.test.js
  src/components/articles/test/UpdateArticleForm.test.js
  src/components/articles/test/createArticle.test.js
  src/components/auth/change_password.js
  src/components/auth/change_password.test.js
  src/components/auth/reset_password.js
  src/components/auth/reset_password.test.js
  src/reducers/likeArticleReducer.js
  src/reducers/passwordResetReducer.test.js
  src/reducers/rootReducer.js
  src/reducers/tests/likeArticleReducer.test.js
  tests/jest.config.js
Labels: Ready for Reviews

#36 #162633481 Implements Comment History
  .github/pull_request_template.md
  package.json
  src/assets/css/style.css
  src/components/Bookmarks/bookmarkArticle.js
  src/components/articles/SingleArticle.js
  src/components/articles/SingleArticleItem.js
  src/components/articles/SingleArticleView.js
  src/components/comments/CommentHistory.js
  src/components/comments/CommentList.js
  src/components/comments/EditComment.js
  src/components/comments/SingleComment.js
  src/components/comments/SingleCommentButtons.js
  src/components/comments/actions/actions.js
  src/components/comments/actions/commentHistoryActions.js
  src/components/comments/tests/CommentHistory.test.js
  src/components/comments/tests/SingleComment.test.js
  src/components/pagination/pageItem.js
Labels: Ready for Reviews

#41 #162633468 Implements Like or dislike articles by a user
  package-lock.json
  src/actions/ChangePasswordAction.test.js
  src/actions/ResetPasswordLinkAction.js
  src/actions/ResetPasswordLinkAction.test.js
  src/actions/likeArticleActions.js
  src/actions/tests/likeActions.test.js
  src/components/articles/CreateArticle.js
  src/components/articles/LikeArticle.js
  src/components/articles/SingleArticleView.js
  src/components/articles/UpdateArticle.js
  src/components/articles/UpdateArticleForm.js
  src/components/articles/test/CreateArticleForm.test.js
  src/components/articles/test/LikeArticle.test.js
  src/components/articles/test/UpdateArticle.test.js
  src/components/articles/test/UpdateArticleForm.test.js
  src/components/articles/test/createArticle.test.js
  src/components/auth/change_password.js
  src/components/auth/change_password.test.js
  src/components/auth/reset_password.js
  src/components/auth/reset_password.test.js
  src/reducers/likeArticleReducer.js
  src/reducers/passwordResetReducer.test.js
  src/reducers/rootReducer.js
  src/reducers/tests/likeArticleReducer.test.js
  tests/jest.config.js
Labels: Finished

#37 162633483 Implements reading stats for a user's articles
  package-lock.json
  package.json
  src/actions/stats/ReadingStatsAction.js
  src/actions/stats/actionTypes.js
  src/actions/stats/tests/ReadingStatsAction.test.js
  src/assets/css/profile.css
  src/assets/css/style.css
  src/components/articles/ReadingStats.js
  src/components/articles/SingleArticleItem.js
  src/components/articles/test/ReadingStats.test.js
  src/components/profile/ProfileTabs.js
  src/reducers/rootReducer.js
  src/reducers/stats/statReducer.js
  src/reducers/stats/tests/statReducer.test.js
Labels: Ready for Reviews
